### ISSUE TITLE
Now I want to study deeply.

### ISSUE THREAD

**Issue by chlwlscjf** [MicrosoftDocs/visualstudio-docs.ko-kr#11]
[여기에 피드백 입력]

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: f307022f-0b34-372f-2185-b61227c110a7
* Version Independent ID: feabd94b-8396-4c5c-cbb4-cad94f2a476f
* Content: [Visual Studio 2017 설치 문제 해결](https://docs.microsoft.com/ko-kr/visualstudio/install/troubleshooting-installation-issues)
* Content Source: [docs/install/troubleshooting-installation-issues.md](https://github.com/MicrosoftDocs/visualstudio-docs.ko-kr/blob/live/docs/install/troubleshooting-installation-issues.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by LisandroSu** [comment]
Hello, @chlwlscjf  
  
Thank you for your feedback. 
  
Can you provide us more information about the nature of your issue?
 
Kind regards, 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @chlwlscjf,
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
