### ISSUE TITLE
예제에 문제가 있어 문의 드립니다.

### ISSUE THREAD

**Issue by psh9508** [MicrosoftDocs/visualstudio-docs.ko-kr#127]
안녕하세요. 이 페이지의 예제중에

아래 코드를 IntelliSense의 자동완성을 시연하는 과정에서

아래와 같은 문제가 있으니 확인 해보시기 바랍니다.

int a = 42;
int b = 119;
int c = a + b; // 이 부분이 빠져있습니다.
Console.WriteLine(c);
Console.ReadKey();

이상입니다.
감사합니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: f783f152-b26c-0ea4-8017-3929c7465368
* Version Independent ID: 8777c084-6578-8a7f-89db-80b3f9d547a7
* Content: [자습서: 간단한 C# 콘솔 앱 만들기 - Visual Studio](https://docs.microsoft.com/ko-kr/visualstudio/get-started/csharp/tutorial-console?view=vs-2019#feedback)
* Content Source: [docs/get-started/csharp/tutorial-console.md](https://github.com/MicrosoftDocs/visualstudio-docs.ko-kr/blob/live/docs/get-started/csharp/tutorial-console.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by srvbpigh** [comment]
Hello, @psh9508
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
안녕하세요, @psh9508님.  

귀하의 기여에 매우 감사 드립니다. 귀하의 피드백은 원본 설명서와 관련되어 있습니다.  

따라서 이 문제를 영어 리포지토리에 마이그레이션하고 있습니다. 여기 - https://github.com/MicrosoftDocs/visualstudio-docs/issues/4836에서 문제 상태를 확인하세요.  

당사 문서에 대한 귀하의 기여에 진심으로 감사 드립니다.   

감사합니다.  
Microsoft DOCS 국제 팀
