### ISSUE TITLE
타이틀 오탈자

### ISSUE THREAD

**Issue by sukbu** [MicrosoftDocs/visualstudio-docs.ko-kr#136]
코드 기호 이름 바꾸기 래픽터링
=&gt; 리팩토링/리팩터링

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: d231e9f6-7c0c-7073-6727-81a08019e589
* Version Independent ID: d0078914-0fc3-e988-ce0e-559c09f0b4c8
* Content: [리팩터링 이름 바꾸기 - Visual Studio](https://docs.microsoft.com/ko-kr/visualstudio/ide/reference/rename?view=vs-2019#feedback)
* Content Source: [docs/ide/reference/rename.md](https://github.com/MicrosoftDocs/visualstudio-docs.ko-kr/blob/live/docs/ide/reference/rename.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by srvbpigh** [comment]
Hello, @sukbu
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
안녕하세요, @sukbu님.   

피드백을 주셔서 감사합니다.  

당사의 언어 팀이 귀하의 언어 제안을 검토하고 수용했습니다. 귀하의 피드백을 반영하여 Docs 사이트의 업데이트된 문서의 다음 페이지 https://docs.microsoft.com/ko-kr/visualstudio/ide/reference/rename?view=vs-2019#feedback에 게시했습니다.   

당사의 문서에 대한 귀하의 기여에 진심으로 감사 드리며 소중한 피드백을 계속 주시기 바랍니다.  

감사합니다.  
Microsoft DOCS 국제 팀

**Comment by sukbu** [comment]
![image](https://user-images.githubusercontent.com/33961582/80912184-297df780-8d76-11ea-8cbb-6a84c6cf71ae.png)

It still haven't changed sir.
