### ISSUE TITLE
Not opened Project designer(property) page window

### ISSUE THREAD

**Issue by HyunmokMoon** [MicrosoftDocs/visualstudio-docs.ko-kr#140]
[여기에 피드백 입력]

In some project, I can not open project property window.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: db2f3877-b9ea-1ee4-b4ab-ec146139cf5b
* Version Independent ID: b9e98d4e-1053-4ac3-f1f0-a31c12e72f6f
* Content: [C# 프로젝트 속성의 애플리케이션 페이지 - Visual Studio](https://docs.microsoft.com/ko-kr/visualstudio/ide/reference/application-page-project-designer-csharp?view=vs-2019)
* Content Source: [docs/ide/reference/application-page-project-designer-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs.ko-kr/blob/live/docs/ide/reference/application-page-project-designer-csharp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by srvbpigh** [comment]
Hello, @HyunmokMoon
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @HyunmokMoon 

Your contribution is highly appreciated. Yet, this feedback is related with product, please kindly log your suggestion by using the button "Give Product Feedback" at the bottom of the DOCS page. 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles. 

Microsoft DOCS International Team
