### ISSUE TITLE
Range.value2 사용시 차트에 연결된 Excel깨짐현상

### ISSUE THREAD

**Issue by gimapei** [MicrosoftDocs/visualstudio-docs.ko-kr#143]
[여기에 피드백 입력]
Powerpoint VSTO를 c#으로 만들었습니다. 
Range.Value2로 Array Data를 설정하면
다음번에 powerpoint를 열어 해당차트의 데이타를 수정하려고하면
반드시 excel이 깨져서 열리지 않고수정할수 없게됩니다. 

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 90a72ddb-5e57-3d00-7675-75430830cbb0
* Version Independent ID: 59c6e5d2-7a6f-e5f2-0b32-2c7557a9a7aa
* Content: [방법: 프로그래밍 방식으로 코드에서 워크시트 범위 참조 - Visual Studio](https://docs.microsoft.com/ko-kr/visualstudio/vsto/how-to-programmatically-refer-to-worksheet-ranges-in-code?view=vs-2019)
* Content Source: [docs/vsto/how-to-programmatically-refer-to-worksheet-ranges-in-code.md](https://github.com/MicrosoftDocs/visualstudio-docs.ko-kr/blob/live/docs/vsto/how-to-programmatically-refer-to-worksheet-ranges-in-code.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by srvbpigh** [comment]
Hello, @gimapei
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
안녕하세요 @gimapei  님, 
 
기여해 주셔서 정말 감사드립니다. 죄송하지만 해당 피드백은 제품과 관련이 있습니다. DOCS 페이지 아래에 있는 “제품 피드백 제공” 단추를 사용하여 제안을 기록해 주세요. 
 
설명서와 관련한 피드백이 있으시면 본 채널을 통해 피드백을 기록해 주세요. 

Microsoft 문서에 기여해 주셔서 진심으로 감사드립니다. 

Microsoft DOCS 국제 팀
