### ISSUE TITLE
The install path of Visual Studio 2017 for AI

### ISSUE THREAD

**Issue by BradJeong** [MicrosoftDocs/visualstudio-docs.ko-kr#17]
[여기에 피드백 입력]
It's very easy to install it with Anaconda Navigator. 
And, you have to change the installed default path of Anaconda and Python from "C:\Program Files (x86)\Microsoft Visual Studio\Shared\" to the other path.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 2af0159a-9ca0-860c-18f7-a406c1703962
* Version Independent ID: 2f2c29d0-13fd-ec19-2005-d56a7740ad92
* Content: [AI Tools for Visual Studio 설치 - Visual Studio](https://docs.microsoft.com/ko-kr/visualstudio/ai/installation?view=vs-2017)
* Content Source: [docs/ai/installation.md](https://github.com/MicrosoftDocs/visualstudio-docs.ko-kr/blob/live/docs/ai/installation.md)
* Service: **multiple**
* Product: **visual-studio-dev15**
* GitHub Login: @lisawong19
* Microsoft Alias: **liwong**

**Comment by LisandroSu** [comment]
Hello, @BradJeong ,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
