### ISSUE TITLE
매우 좋은 기능

### ISSUE THREAD

**Issue by joanpark** [MicrosoftDocs/visualstudio-docs.ko-kr#50]
자주 쓰는 포맷의 클래스 추가시 미리 템플릿을 만들어 놓고 추가하면 시간 절약

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 8e44d5ce-a797-8367-d4d0-0c3a29f0b18c
* Version Independent ID: d3203ea3-2a1b-f418-62a9-0024c5e03685
* Content: [항목 템플릿 만들기 - Visual Studio](https://docs.microsoft.com/ko-kr/visualstudio/ide/how-to-create-item-templates?view=vs-2019#feedback)
* Content Source: [docs/ide/how-to-create-item-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs.ko-kr/blob/live/docs/ide/how-to-create-item-templates.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by lichasu** [comment]
Hello, @joanpark ,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
